more turndown

diff --git a/src/BlogSrc/2007-12-12-713 b/src/BlogSrc/2007-12-12-713
--- a/src/BlogSrc/2007-12-12-713
+++ b/src/BlogSrc/2007-12-12-713
@@ -3,64 +3,68 @@ TITLE=Downsample
 DATE=2007-12-12 12:40:06
 POSTID=713
 CATEGORIES=computers-code;
-MODE=htmldiv
 
-<p>I can't tell the difference between a 32KBps and 224KBps mp3 file.  Can you?</p>
-<p>So I'm down-sampling all my mp3s to fit on my new mp3 player.  I should be able to fit around 3 days of music onto my 1GB player this way.</p>
-<p>Here's a script to do that---a work in progress</p>
-<pre>#!/bin/sh
+I can't tell the difference between a 32KBps and 224KBps mp3 file. Can you?
 
-## Compressmp3s - Copyright 2007 Hal Canary
-## Dedicated to the Public Domain.
+So I'm down-sampling all my mp3s to fit on my new mp3 player. I should be able to fit around 3 days of music onto my 1GB player this way.
 
-## Arguments: a list of directories to search for mp3s
-## This script will use lame to create a 32kbps version
-## of those mp3 and save it in a subdirectory of $TARGETDIR
+Here's a script to do that---a work in progress
 
-if [ &quot;$#&quot; -lt 1 ] ; then
-    echo &quot;Give me an argument!&quot;
-    exit 1
-fi
-
-TARGETDIR=&quot;$HOME/tmp/CompressedAudio&quot;
-mkdir -p &quot;$TARGETDIR&quot; || {
-    echo &quot;Use a directory you have permissions for.&quot;;
-    exit 1 ; }
-
-## for FILE in &quot;$@&quot; ; do
-find &quot;$@&quot; -name '*.mp3' | while read FILE; do
-    IN=&quot;$FILE&quot;
-    OUT=&quot;${TARGETDIR}/$FILE&quot;
-    ## Grab the id3 info for later use
-    artist=`id3info &quot;$IN&quot; | grep TPE1 | &#0092;
-        awk -F ': ' '{print $2}'`
-    album=`id3info &quot;$IN&quot; | grep TALB | &#0092;
-        awk -F ': ' '{print $2}'`
-    track=`id3info &quot;$IN&quot; | grep TRCK | &#0092;
-        awk -F ': ' '{print $2}'`
-    song=`id3info &quot;$IN&quot; | grep TIT2 | &#0092;
-        awk -F ': ' '{print $2}'`
-    echo &quot;$OUT&quot;
-    ## refuse to clobber a file
-    if [ ! -f &quot;$OUT&quot; ] ; then
-        echo &quot;  artist=$artist&quot;
-        echo &quot;  album=$album&quot;
-        echo &quot;  track=$track&quot;
-        echo &quot;  song=$song&quot;
-        echo &quot;&quot;
-        DIRECTORY=`dirname &quot;$OUT&quot;`
-        mkdir -p &quot;$DIRECTORY&quot; || { echo &quot;permission error&quot; ;
-            exit 1 ; }
-        lame -b 32 &quot;$IN&quot; &quot;$OUT&quot; &#0092;
-            --ta &quot;$artist&quot; --tl &quot;$album&quot; &#0092;
-            --tn &quot;$track&quot; --tt &quot;$song&quot; &#0092;
-            --add-id3v2
-    else
-        echo &quot;  already exists!&quot;
+    #!/bin/sh
+    
+    ## Compressmp3s - Copyright 2007 Hal Canary
+    ## Dedicated to the Public Domain.
+    
+    ## Arguments: a list of directories to search for mp3s
+    ## This script will use lame to create a 32kbps version
+    ## of those mp3 and save it in a subdirectory of $TARGETDIR
+    
+    if [ "$#" -lt 1 ] ; then
+        echo "Give me an argument!"
+        exit 1
     fi
-done
-</pre>
-<p>Okay, on some files, I *can* tell the difference.</p>
-<p>* * *</p>
-<p>Compare:  <a href="/pub/hidden/Nb99cbhCIxWy7ddxYPNU/032kbps_Catfish_and_the_One_Eyed_Jacks_-_The_Way_You_Move_01_-_Move_.mp3">032kbps mp3</a> versus <a href="/pub/hidden/Nb99cbhCIxWy7ddxYPNU/128kbps_Catfish_and_the_One_Eyed_Jacks_-_The_Way_You_Move_01_-_Move_.mp3">128kbps mp3</a>.</p>
+    
+    TARGETDIR="$HOME/tmp/CompressedAudio"
+    mkdir -p "$TARGETDIR" || {
+        echo "Use a directory you have permissions for.";
+        exit 1 ; }
+    
+    ## for FILE in "$@" ; do
+    find "$@" -name '*.mp3' | while read FILE; do
+        IN="$FILE"
+        OUT="${TARGETDIR}/$FILE"
+        ## Grab the id3 info for later use
+        artist=`id3info "$IN" | grep TPE1 | \
+            awk -F ': ' '{print $2}'`
+        album=`id3info "$IN" | grep TALB | \
+            awk -F ': ' '{print $2}'`
+        track=`id3info "$IN" | grep TRCK | \
+            awk -F ': ' '{print $2}'`
+        song=`id3info "$IN" | grep TIT2 | \
+            awk -F ': ' '{print $2}'`
+        echo "$OUT"
+        ## refuse to clobber a file
+        if [ ! -f "$OUT" ] ; then
+            echo "  artist=$artist"
+            echo "  album=$album"
+            echo "  track=$track"
+            echo "  song=$song"
+            echo ""
+            DIRECTORY=`dirname "$OUT"`
+            mkdir -p "$DIRECTORY" || { echo "permission error" ;
+                exit 1 ; }
+            lame -b 32 "$IN" "$OUT" \
+                --ta "$artist" --tl "$album" \
+                --tn "$track" --tt "$song" \
+                --add-id3v2
+        else
+            echo "  already exists!"
+        fi
+    done
+    
 
+Okay, on some files, I \*can\* tell the difference.
+
+\* \* \*
+
+Compare: [032kbps mp3](/pub/hidden/Nb99cbhCIxWy7ddxYPNU/032kbps_Catfish_and_the_One_Eyed_Jacks_-_The_Way_You_Move_01_-_Move_.mp3) versus [128kbps mp3](/pub/hidden/Nb99cbhCIxWy7ddxYPNU/128kbps_Catfish_and_the_One_Eyed_Jacks_-_The_Way_You_Move_01_-_Move_.mp3).
diff --git a/src/BlogSrc/2011-11-08-csg18 b/src/BlogSrc/2011-11-08-csg18
--- a/src/BlogSrc/2011-11-08-csg18
+++ b/src/BlogSrc/2011-11-08-csg18
@@ -2,58 +2,60 @@ COPYRIGHT=Copyright Hal Canary / ALL RIGHTS RESERVED
 TITLE=snap your window to the left or right
 DATE=2011-11-08 12:00:00
 POSTID=csg18
-MODE=htmldiv
 
-<p>This script will snap your window to the left or right side of the screen in Linux:
-(<a href="http://www.techsupportalert.com/content/ubuntu-tips-and-tricks.htm#Enable-Aero-Snap">SOURCE</a>)</p>
-<pre>
-#!/bin/sh
-## ${HOME}/bin/wmctrl&#0045;snap&#0045;edge
-#DTPD#
-WMCTRL=&quot;${HOME}/bin/wmctrl_`arch`&quot;
-#WMCTRL=&quot;/usr/bin/wmctrl&quot;
-test &#0045;x &quot;/usr/bin/xdpyinfo&quot; &#0045;a &#0045;x &quot;$WMCTRL&quot; || {
-    echo &quot;error&quot;; exit 1; }
+This script will snap your window to the left or right side of the screen in Linux: ([SOURCE](http://www.techsupportalert.com/content/ubuntu-tips-and-tricks.htm#Enable-Aero-Snap))
 
-WIDTH=`xdpyinfo | sed &#0045;n &#0039;s/ *dimensions: *&#0092;([0&#0045;9]*&#0092;)x.*/&#0092;1/p&#0039;`
-HALF=$(($WIDTH / 2));
-&quot;$WMCTRL&quot; &#0045;r :ACTIVE: &#0045;b add,maximized_vert;
-if test &quot;$1&quot; = &quot;left&quot; ; then
-	&quot;$WMCTRL&quot; &#0045;r :ACTIVE: &#0045;e 0,0,0,$HALF,&#0045;1
-elif test &quot;$1&quot; = &quot;right&quot; ; then
-	&quot;$WMCTRL&quot; &#0045;r :ACTIVE: &#0045;e 0,$HALF,0,$HALF,&#0045;1
-fi
-</pre>
+    
+    #!/bin/sh
+    ## ${HOME}/bin/wmctrl-snap-edge
+    #DTPD#
+    WMCTRL="${HOME}/bin/wmctrl_`arch`"
+    #WMCTRL="/usr/bin/wmctrl"
+    test -x "/usr/bin/xdpyinfo" -a -x "$WMCTRL" || {
+        echo "error"; exit 1; }
+    
+    WIDTH=`xdpyinfo | sed -n 's/ *dimensions: *\([0-9]*\)x.*/\1/p'`
+    HALF=$(($WIDTH / 2));
+    "$WMCTRL" -r :ACTIVE: -b add,maximized_vert;
+    if test "$1" = "left" ; then
+    	"$WMCTRL" -r :ACTIVE: -e 0,0,0,$HALF,-1
+    elif test "$1" = "right" ; then
+    	"$WMCTRL" -r :ACTIVE: -e 0,$HALF,0,$HALF,-1
+    fi
+    
 
-<p>If you don't have wmctrl installed, you can apt-get it (Ubuntu):</p>
-<pre>sudo apt&#0045;get &#0045;&#0045;yes install wmctrl</pre>
+If you don't have wmctrl installed, you can apt-get it (Ubuntu):
+
+    sudo apt-get --yes install wmctrl
+
 Or compile it yourself:
-<pre>
-sudo yum install libXmu&#0045;devel
-cd /tmp
-wget &#0039;http://tomas.styblo.name/wmctrl/dist/wmctrl&#0045;1.07.tar.gz&#0039;
-tar &#0045;&#0045;extract &#0045;&#0045;gzip &#0045;&#0045;file &quot;wmctrl&#0045;1.07.tar.gz&quot;
-cd wmctrl&#0045;1.07
-./configure
-make &#0045;j 4
-mv wmctrl ${HOME}/bin/wmctrl_`arch`
-</pre>
 
-<p>The next step is to set up hotkeys.  If you use Metacity like I do, then:</p>
-<pre>
-gconftool&#0045;2 &#0045;&#0045;type string &#0045;&#0045;set &#0092;
-	/apps/metacity/global_keybindings/run_command_6 &#0092;
-	&#0039;&lt;Ctrl&gt;&lt;Alt&gt;Page_Up&#0039;
+    
+    sudo yum install libXmu-devel
+    cd /tmp
+    wget 'http://tomas.styblo.name/wmctrl/dist/wmctrl-1.07.tar.gz'
+    tar --extract --gzip --file "wmctrl-1.07.tar.gz"
+    cd wmctrl-1.07
+    ./configure
+    make -j 4
+    mv wmctrl ${HOME}/bin/wmctrl_`arch`
+    
 
-gconftool&#0045;2 &#0045;&#0045;type string &#0045;&#0045;set &#0092;
-	/apps/metacity/keybinding_commands/command_6 &#0092;
-	&quot;${HOME}/bin/wmctrl&#0045;snap&#0045;edge left&quot;
+The next step is to set up hotkeys. If you use Metacity like I do, then:
 
-gconftool&#0045;2 &#0045;&#0045;type string &#0045;&#0045;set &#0092;
-	/apps/metacity/global_keybindings/run_command_7 &#0092;
-	&#0039;&lt;Ctrl&gt;&lt;Alt&gt;Page_Down&#0039;
-
-gconftool&#0045;2 &#0045;&#0045;type string &#0045;&#0045;set &#0092;
-	/apps/metacity/keybinding_commands/command_7 &#0092;
-	&quot;${HOME}/bin/wmctrl&#0045;snap&#0045;edge right&quot;
-</pre>
+    
+    gconftool-2 --type string --set \
+    	/apps/metacity/global_keybindings/run_command_6 \
+    	'<Ctrl><Alt>Page_Up'
+    
+    gconftool-2 --type string --set \
+    	/apps/metacity/keybinding_commands/command_6 \
+    	"${HOME}/bin/wmctrl-snap-edge left"
+    
+    gconftool-2 --type string --set \
+    	/apps/metacity/global_keybindings/run_command_7 \
+    	'<Ctrl><Alt>Page_Down'
+    
+    gconftool-2 --type string --set \
+    	/apps/metacity/keybinding_commands/command_7 \
+    	"${HOME}/bin/wmctrl-snap-edge right"
